CREATE TABLE `book`(
`ID` int(10) NOT NULL AUTO_INCREMENT,
`NOM` varchar(50) NOT NULL,
`AUTEUR` varchar(50) NOT NULL,
`ANNEE` varchar(4) NOT NULL,
`DOMAINE` varchar(50) NOT NULL,
PRIMARY KEY (`ID`)
);